# coding: utf-8


class LatexTableGeneratorError(Exception): ...


class NotDetectTableError(LatexTableGeneratorError): ...


class NotColumnMatchError(LatexTableGeneratorError): ...


class ImagePasteError(LatexTableGeneratorError): ...


class NotLatexError(LatexTableGeneratorError): ...


class NotSupportLatexError(LatexTableGeneratorError): ...


class NotSupportMultiLatexTableError(NotSupportLatexError): ...
