# coding: utf-8


class FormatError(Exception): ...


class LatexTableGeneratorError(Exception): ...


class NotDetectTableError(LatexTableGeneratorError): ...


class NotColumnMatchError(LatexTableGeneratorError): ...


class ImagePasteError(LatexTableGeneratorError): ...


class NotHtmlError(LatexTableGeneratorError, FormatError): ...


class NotLatexError(LatexTableGeneratorError, FormatError): ...


class NotSupportLatexError(LatexTableGeneratorError, FormatError): ...


class NotSupportMultiLatexTableError(NotSupportLatexError): ...
