[
    {"choices": None, "hashtag": False, "names": ["項次"], "range": [1, 8], "sequence": True, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["直徑(mm)"], "range": [10, 13], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["間距(cm)"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["單支長(cm)"], "range": [110, 640], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數(支)"], "range": [60, 130], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長(cm)"], "range": [11550, 60000], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重(kg/m)"], "range": [56, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 0], "sequence": False, "type": "int"},
    {
        "choices": ["洗車台底板", "洗車台底板+牆副筋", "滯洪池底板", "滯洪池牆身"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
