[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 63], "sequence": True, "type": "int"},
    {
        "choices": ["彎料", "寬料", "直料"],
        "hashtag": False,
        "names": ["組編號", "項編號"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長A", "長 A"], "range": [8, 122], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示/長度B",
            "施工內容/長度B",
            "加工形狀/長度B",
            "加工型狀/長度B",
            "加工形式/長度B",
            "加工型式/長度B",
            "形狀/長度B",
            "型狀/長度B",
            "形式/長度B",
            "型式/長度B",
            "料型/長度B",
            "料形/長度B",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": ["-", ""], "hashtag": False, "names": ["長C"], "range": None, "sequence": False, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [12, 1050], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 3236], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [5, 8363], "sequence": False, "type": "int"},
    {
        "choices": ["穿樑", "窗上立筋", "定身", "穿樑補強", "籃框"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
