[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 22], "sequence": True, "type": "int"},
    {"choices": ["直料", "彎料"], "hashtag": False, "names": ["組編號"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 4], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長A"], "range": [15, 20], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示/長度B",
            "施工內容/長度B",
            "加工形狀/長度B",
            "加工型狀/長度B",
            "加工形式/長度B",
            "加工型式/長度B",
            "形狀/長度B",
            "型狀/長度B",
            "形式/長度B",
            "型式/長度B",
            "料型/長度B",
            "料形/長度B",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長C"], "range": [130, 800], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [6, 150], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [10, 496], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 22], "sequence": True, "type": "int"},
    {"choices": ["直料", "彎料"], "hashtag": False, "names": ["組編號"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 4], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長A"], "range": [15, 20], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示/長度B",
            "施工內容/長度B",
            "加工形狀/長度B",
            "加工型狀/長度B",
            "加工形式/長度B",
            "加工型式/長度B",
            "形狀/長度B",
            "型狀/長度B",
            "形式/長度B",
            "型式/長度B",
            "料型/長度B",
            "料形/長度B",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長C"], "range": [130, 800], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [6, 150], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [10, 496], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
