[
    {"choices": None, "hashtag": False, "names": ["項次"], "range": [11, 12], "sequence": True, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["直徑(mm)"], "range": [13, 19], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["間距(cm)"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["單支長(cm)"], "range": [1200, 1200], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數(支)"], "range": [340, 2510], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長(cm)"], "range": [408000, 3012000], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重(kg/m)"], "range": [25, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 0], "sequence": False, "type": "int"},
    {"choices": ["工作筋+內箍筋", "外箍筋"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["項次"], "range": [11, 12], "sequence": True, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["直徑(mm)"], "range": [13, 19], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["間距(cm)"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["單支長(cm)"], "range": [1200, 1200], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數(支)"], "range": [340, 2510], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長(cm)"], "range": [408000, 3012000], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重(kg/m)"], "range": [25, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 0], "sequence": False, "type": "int"},
    {"choices": ["工作筋+內箍筋", "外箍筋"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
