[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 66], "sequence": True, "type": "int"},
    {"choices": ["彎料", "直料"], "hashtag": False, "names": ["組編號"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長A"], "range": [10, 120], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示/長度B",
            "施工內容/長度B",
            "加工形狀/長度B",
            "加工型狀/長度B",
            "加工形式/長度B",
            "加工型式/長度B",
            "形狀/長度B",
            "型狀/長度B",
            "形式/長度B",
            "型式/長度B",
            "料型/長度B",
            "料形/長度B",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長C"], "range": [10, 120], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [40, 940], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 1450], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [5, 3370], "sequence": False, "type": "int"},
    {"choices": ["定身"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 66], "sequence": True, "type": "int"},
    {"choices": ["彎料", "直料"], "hashtag": False, "names": ["組編號"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長A"], "range": [10, 120], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示/長度B",
            "施工內容/長度B",
            "加工形狀/長度B",
            "加工型狀/長度B",
            "加工形式/長度B",
            "加工型式/長度B",
            "形狀/長度B",
            "型狀/長度B",
            "形式/長度B",
            "型式/長度B",
            "料型/長度B",
            "料形/長度B",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長C"], "range": [10, 120], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [40, 940], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 1450], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [5, 3370], "sequence": False, "type": "int"},
    {"choices": ["定身"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
