[
    {"choices": None, "hashtag": False, "names": ["#", "\\#"], "range": [1, 100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度", "長 度"], "range": [46, 1250], "sequence": False, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["數  量", "數量", "數 量"],
        "range": [1, 55160],
        "sequence": False,
        "type": "int",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量Kg", "重量 (Kg)", "重量 Kg", "重量(Kg)"],
        "range": [1, 2037],
        "sequence": False,
        "type": "int",
    },
    {
        "choices": ["定尺", "電表箱開口筋"],
        "hashtag": False,
        "names": ["備 註", "備-註", "備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
    {"choices": None, "hashtag": False, "names": ["#", "\\#"], "range": [1, 100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度", "長 度"], "range": [46, 1250], "sequence": False, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["數  量", "數量", "數 量"],
        "range": [1, 55160],
        "sequence": False,
        "type": "int",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量Kg", "重量 (Kg)", "重量 Kg", "重量(Kg)"],
        "range": [1, 2037],
        "sequence": False,
        "type": "int",
    },
    {
        "choices": ["定尺", "電表箱開口筋"],
        "hashtag": False,
        "names": ["備 註", "備-註", "備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
]
