[
    {"choices": None, "hashtag": False, "names": ["#"], "range": [1, 100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度"], "range": [330, 650], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [8, 253], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["重量 Kg"], "range": [7, 11], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["備註"], "range": [8, 10], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["#"], "range": [1, 100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度"], "range": [330, 650], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [8, 253], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["重量 Kg"], "range": [7, 11], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["備註"], "range": [8, 10], "sequence": False, "type": "int"},
]
