[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 100], "sequence": True, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 100], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度(cm)"],
        "range": [55, 600],
        "sequence": False,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 490], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 1948], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 100], "sequence": True, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 100], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度(cm)"],
        "range": [55, 600],
        "sequence": False,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 490], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 1948], "sequence": False, "type": "int"},
]
