[
    {
        "choices": ["牆預留", "樓梯子", "版", "主筋", "樓梯料", "馬仔", "基礎", "工作筋", "補強筋", "副筋"],
        "hashtag": False,
        "names": ["部位", "編號"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度", "長度(cm)"], "range": [40, 850], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量", "支數"], "range": [4, 685], "sequence": False, "type": "int"},
    {"choices": ["機坑基礎", "維修孔"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
