[
    {
        "choices": ["樓梯料", "樓梯子", "補強筋", "女兒牆"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [4, 6], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度"], "range": [0, 45687], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [16, 125], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {
        "choices": ["樓梯料", "樓梯子", "補強筋", "女兒牆"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [4, 6], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度"], "range": [0, 45687], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [16, 125], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
