[
    {
        "choices": ["樑", "電梯牆", "柱補", "上版補", "牆預留", "牆", "樑補", "擴樑", "上版", "牆補", "柱", "下版", "假柱"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": False, "names": ["號數"], "range": [3, 10], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["加工總長", "長度"], "range": [35, 1150], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["交數", "支數"], "range": [1, 3584], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [3, 10051], "sequence": False, "type": "int"},
]
