[
    {"choices": [], "hashtag": False, "names": ["#", "\\#"], "range": None, "sequence": False, "type": "str"},
    {"choices": [], "hashtag": False, "names": ["長度"], "range": None, "sequence": False, "type": "str"},
    {"choices": [], "hashtag": False, "names": ["數量"], "range": None, "sequence": False, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["重量 Kg"], "range": [0, 45687], "sequence": False, "type": "int"},
    {"choices": ["抗拉備料"], "hashtag": False, "names": ["備註"], "range": None, "sequence": False, "type": "str"},
    {"choices": [], "hashtag": False, "names": ["#", "\\#"], "range": None, "sequence": False, "type": "str"},
    {"choices": [], "hashtag": False, "names": ["長度"], "range": None, "sequence": False, "type": "str"},
    {"choices": [], "hashtag": False, "names": ["數量"], "range": None, "sequence": False, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["重量 Kg"], "range": [0, 45687], "sequence": False, "type": "int"},
    {"choices": ["抗拉備料"], "hashtag": False, "names": ["備註"], "range": None, "sequence": False, "type": "str"},
]
