[
    {"choices": ["樑箍", "樑箍蓋"], "hashtag": False, "names": ["部位"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 4], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度"], "range": [55, 1050], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [4, 180], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [135, 180], "sequence": False, "type": "int"},
]
