[
    {"choices": ["牆補"], "hashtag": False, "names": ["部位"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["號數"], "range": [3, 4], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["加工總長"], "range": [120, 600], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [20, 250], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [0, 45687], "sequence": None, "type": "int"},
]
