[
    {"choices": None, "hashtag": True, "names": ["編號"], "range": [1, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [150, 750], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [1, 122], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [6, 3108], "sequence": False, "type": "int"},
    {
        "choices": ["粱T頭,請單一捆進工地", "試驗用"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
