[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 182], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": None, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度(cm)"],
        "range": [35, 1300],
        "sequence": None,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [1, 3550], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [1, 6687], "sequence": None, "type": "int"},
    {
        "choices": [
            "擴樑箍",
            "擴樑腰筋",
            "角隅",
            "穿樑套管補強",
            "雙腳椅馬",
            "雙腳椅馬樓梯版",
            "甘蔗",
            "預備料",
            "柱收頭",
            "立體 彎鉤向下",
            "甘蔗節",
            "腰-圖弧筋",
            "角隅補強",
            "加厚版用雙腳椅馬",
            "安全彎鉤",
            "S型椅馬",
            "穿管補強",
            "工作椅",
            "補料",
            "T頭",
            "增築",
            "中間柱補強",
            "擴樑",
            "開口補強",
            "加厚板用 雙腳椅馬",
            "立體 彎鉤向上",
            "工作筋",
            "模板用",
            "雙頭",
        ],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
