[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 16], "sequence": True, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["號數"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": ["模板用"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 16], "sequence": True, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["號數"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 45687], "sequence": None, "type": "int"},
    {"choices": ["模板用"], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
