[
    {
        "choices": None,
        "hashtag": False,
        "names": ["編號", "編號."],
        "range": [1, 234],
        "sequence": True,
        "type": "int",
    },
    {"choices": None, "hashtag": True, "names": ["\\#4", "號數", "\\#3"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度(cm)"],
        "range": [30, 1300],
        "sequence": False,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 3520], "sequence": False, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量(kg).", "重量(kg)"],
        "range": [0, 25781],
        "sequence": False,
        "type": "int",
    },
    {
        "choices": [
            "擴柱",
            "造型柱",
            "擴柱樑柱箍",
            "現場用不到",
            "擴樑箍",
            "腰",
            "穿樑套管補強",
            "母頭",
            "收頭用",
            "雙腳椅馬",
            "圓弧筋",
            "甘蔗",
            "腰 圆弧筋",
            "預備料",
            "角隅",
            "前CS版",
            "立體, 彎鉤向下",
            "預留",
            "版",
            "電梯對力牆",
            "柱增築",
            "造型柱用",
            "垂牆用",
            "柱擴柱",
            "柱收頭",
            "地梁斜撐",
            "擴",
            "厚牆",
            "牆筋",
            "牆補料",
            "牆立筋",
            "車道",
            "直弧筋",
            "腳角補強牆預留立筋",
            "樓梯",
            "牆 圓弧筋",
            "剪力筋",
            "角隅補強",
            "試驗",
            "電梯剪力牆",
            "牆繫筋",
            "閭窗補強",
            "彎折料",
            "穿梁套管",
            "門窗補強",
            "樑下筋",
            "安全彎鉤",
            "收頭",
            "牆角隅補強用立筋",
            "S型椅馬",
            "牆端用",
            "公頭",
            "折樑",
            "-",
            "穿管補強",
            "梁箍固定",
            "工作椅",
            "備料",
            "馬仔",
            "上增築",
            "T頭",
            "增築",
            "寬止筋",
            "擴樑",
            "壓版箍",
            "穿樑補強",
            "腰筋",
            "加厚板用 雙腳椅馬",
            "試驗用",
            "假柱",
            "工作筋",
            "模板用",
            "補強",
            "雙頭",
            "外圍工作筋",
        ],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["編號", "編號."],
        "range": [1, 234],
        "sequence": True,
        "type": "int",
    },
    {"choices": None, "hashtag": True, "names": ["\\#4", "號數", "\\#3"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度(cm)"],
        "range": [30, 1300],
        "sequence": False,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [0, 3520], "sequence": False, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量(kg).", "重量(kg)"],
        "range": [0, 25781],
        "sequence": False,
        "type": "int",
    },
    {
        "choices": [
            "擴柱",
            "造型柱",
            "擴柱樑柱箍",
            "現場用不到",
            "擴樑箍",
            "腰",
            "穿樑套管補強",
            "母頭",
            "收頭用",
            "雙腳椅馬",
            "圓弧筋",
            "甘蔗",
            "腰 圆弧筋",
            "預備料",
            "角隅",
            "前CS版",
            "立體, 彎鉤向下",
            "預留",
            "版",
            "電梯對力牆",
            "柱增築",
            "造型柱用",
            "垂牆用",
            "柱擴柱",
            "柱收頭",
            "地梁斜撐",
            "擴",
            "厚牆",
            "牆筋",
            "牆補料",
            "牆立筋",
            "車道",
            "直弧筋",
            "腳角補強牆預留立筋",
            "樓梯",
            "牆 圓弧筋",
            "剪力筋",
            "角隅補強",
            "試驗",
            "電梯剪力牆",
            "牆繫筋",
            "閭窗補強",
            "彎折料",
            "穿梁套管",
            "門窗補強",
            "樑下筋",
            "安全彎鉤",
            "收頭",
            "牆角隅補強用立筋",
            "S型椅馬",
            "牆端用",
            "公頭",
            "折樑",
            "-",
            "穿管補強",
            "梁箍固定",
            "工作椅",
            "備料",
            "馬仔",
            "上增築",
            "T頭",
            "增築",
            "寬止筋",
            "擴樑",
            "壓版箍",
            "穿樑補強",
            "腰筋",
            "加厚板用 雙腳椅馬",
            "試驗用",
            "假柱",
            "工作筋",
            "模板用",
            "補強",
            "雙頭",
            "外圍工作筋",
        ],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
