[
    {"choices": ["樑補", "模板"], "hashtag": False, "names": ["部位"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [4, 8], "sequence": None, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度 (cm)", "長度(cm)"], "range": [600, 650], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [20, 140], "sequence": None, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量 (kg)", "重量(kg)", "重量"],
        "range": [517, 835],
        "sequence": None,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [280, 420], "sequence": None, "type": "int"},
    {"choices": ["樑補", "模板"], "hashtag": False, "names": ["部位"], "range": None, "sequence": None, "type": "str"},
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [4, 8], "sequence": None, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度 (cm)", "長度(cm)"], "range": [600, 650], "sequence": None, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [20, 140], "sequence": None, "type": "int"},
    {
        "choices": None,
        "hashtag": False,
        "names": ["重量 (kg)", "重量(kg)", "重量"],
        "range": [517, 835],
        "sequence": None,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [280, 420], "sequence": None, "type": "int"},
]
