[
    {
        "choices": ["牆筋", "模版", "牆", "版筋", "版牆", "模板"],
        "hashtag": False,
        "names": ["部位", "編號"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {
        "choices": None,
        "hashtag": False,
        "names": ["長度 (cm)", "長度(cm)"],
        "range": [65, 1010],
        "sequence": False,
        "type": "int",
    },
    {"choices": None, "hashtag": False, "names": ["數量"], "range": [1, 800], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量 (kg)", "重量(kg)"], "range": [4, 4763], "sequence": False, "type": "int"},
    {
        "choices": ["施工筋", "上板工作筋", "柱托斜角補強", "固定筋", "立體", "斜撐", "隔馬", "工作椅", "馬仔"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
