[
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [40, 1330], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 5020], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(cm)"], "range": [6, 1079300], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [4, 228960], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量 (kg)", "重量(kg)"], "range": [0, 99], "sequence": False, "type": "int"},
    {
        "choices": ["工作筋-樑斜撐", "工作筋-樑固定筋", "工作筋-樑料撐", "工作筋", "樑工作筋", "工作筋-樑馬"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [40, 1330], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 5020], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(cm)"], "range": [6, 1079300], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [4, 228960], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量 (kg)", "重量(kg)"], "range": [0, 99], "sequence": False, "type": "int"},
    {
        "choices": ["工作筋-樑斜撐", "工作筋-樑固定筋", "工作筋-樑料撐", "工作筋", "樑工作筋", "工作筋-樑馬"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
]
