[
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [1, 8], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [60, 1100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 2080], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(cm)"], "range": [700, 950000], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [4, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)"], "range": [0, 97], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [6, 12], "sequence": False, "type": "int"},
]
