[
    {"choices": None, "hashtag": True, "names": ["類別"], "range": [4, 180], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["規格"], "range": [4, 5], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [115, 390], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [9, 1920], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(m)"], "range": [1, 2208], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [56, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總重(kg)"], "range": [512, 756], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": True, "names": ["類別"], "range": [4, 180], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["規格"], "range": [4, 5], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [115, 390], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [9, 1920], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(m)"], "range": [1, 2208], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [56, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總重(kg)"], "range": [512, 756], "sequence": False, "type": "int"},
]
