[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 44], "sequence": True, "type": "int"},
    {
        "choices": ["FSF-內部柱A", "FSF-周邊柱A", "FSF-B區版下層筋"],
        "hashtag": False,
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型狀"], "range": [10, 1215312], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [90, 1060], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 2100], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [12, 3027], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [12, 180], "sequence": False, "type": "int"},
]
