[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 110], "sequence": True, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型狀"], "range": [70, 2010020], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [70, 695], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 5280], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [9, 6646], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [12, 180], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 110], "sequence": True, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型狀"], "range": [70, 2010020], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [70, 695], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 5280], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [9, 6646], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [12, 180], "sequence": False, "type": "int"},
]
