[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 72], "sequence": True, "type": "int"},
    {
        "choices": ["A區版下層筋", "FSF-周邊柱A", "FSF-B區板下層筋", "FSF-B區版上層筋", "A區版下層筋 改直料出貨", "A區版上層筋"],
        "hashtag": False,
        "names": ["施工內容"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型狀"], "range": [10, 80490120], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [90, 1080], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 2870], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [11, 3922], "sequence": False, "type": "int"},
    {
        "choices": ["另外綑綁", "續接器", "開口補強", "角隅補強", "人孔預留", "周邊固定筋", "預留筋", "版差工作筋", "版馬仔"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 72], "sequence": True, "type": "int"},
    {
        "choices": ["A區版下層筋", "FSF-周邊柱A", "FSF-B區板下層筋", "FSF-B區版上層筋", "A區版下層筋 改直料出貨", "A區版上層筋"],
        "hashtag": False,
        "names": ["施工內容"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型狀"], "range": [10, 80490120], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [90, 1080], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [2, 2870], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [11, 3922], "sequence": False, "type": "int"},
    {
        "choices": ["另外綑綁", "續接器", "開口補強", "角隅補強", "人孔預留", "周邊固定筋", "預留筋", "版差工作筋", "版馬仔"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
]
