[
    {"choices": None, "hashtag": False, "names": ["編號"], "range": [1, 132], "sequence": True, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [3, 5], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["型號", "型狀"], "range": [1, 15475180], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [60, 930], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [4, 3152], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量(kg)", "重量kg"], "range": [2, 10092], "sequence": False, "type": "int"},
    {
        "choices": ["另外綑綁", "寬止筋", "止水敦", "開口補強", "角隅補強", "預留筋", "人孔預留", "補強筋"],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
]
