[
    {"choices": [], "hashtag": False, "names": ["編號"], "range": None, "sequence": True, "type": "str"},
    {
        "choices": [
            "水箱底版",
            "車道A版筋",
            "A區版下層工作筋",
            "FSF-B區版下層筋",
            "車道B版筋",
            "A區版筋追加",
            "A區版下層筋追加",
            "A區版下層筋",
            "FSF-周邊柱A",
            "FSF-B區版上層筋",
            "FSF-周邊柱B",
            "東道A版筋",
            "水箱頂版",
            "A區版上層筋追加",
            "車道A樑筋",
            "車道B樑筋",
            "A區壓樑筋",
            "A區版上層筋",
        ],
        "hashtag": False,
        "names": ["施工內容", "施工内容"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
    {"choices": [], "hashtag": False, "names": ["號數"], "range": None, "sequence": False, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["總長度"], "range": [0, 12549], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [0, 12549], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量kg"], "range": [0, 12549], "sequence": False, "type": "int"},
    {
        "choices": [
            "車道版預留",
            "續接器",
            "壓樑筋",
            "止水墩",
            "版馬仔",
            "開口補強",
            "斜撐工作筋",
            "斜撐",
            "預留筋",
            "牆預留筋",
            "補強筋",
        ],
        "hashtag": False,
        "names": ["備註"],
        "range": None,
        "sequence": False,
        "type": "str",
    },
]
