[
    {
        "choices": [
            "消防機房,樓梯,電梯間牆筋",
            "外牆筋,樓梯間牆筋",
            "車道版筋",
            "牆角隅補強筋",
            "車道側牆筋",
            "牆筋",
            "水箱牆筋",
            "下層",
            "電梯牆筋",
            "牆筋寬止筋",
            "水箱版筋",
            "樓梯側牆筋",
            "外牆筋, 樓梯間牆筋",
            "SWI牆筋",
            "上層",
            "補強箍筋",
            "與柱牆同時進料",
            "腰筋",
            "門窗台角隅補強筋",
        ],
        "hashtag": False,
        "names": ["類別"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["規格"], "range": [3, 8], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度", "長度(cm)"], "range": [50, 10301021], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [1, 5548], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度", "總長度(m)"], "range": [1, 8316], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [4, 994], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總重(kg)"], "range": [0, 994], "sequence": False, "type": "int"},
]
