[
    {"choices": [], "hashtag": False, "names": ["類別"], "range": None, "sequence": None, "type": "str"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": True, "names": ["規格"], "range": [3, 3], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["長度(cm)"], "range": [0, 65489], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [0, 65489], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總長度(m)"], "range": [0, 960], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["單位重"], "range": [56, 56], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["總重(kg)"], "range": [0, 880], "sequence": False, "type": "int"},
]
