[
    {
        "choices": ["柱繫筋", "柱料", "預留筋"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [4, 5], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["名稱"], "range": [5, 180], "sequence": False, "type": "int"},
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["料長"], "range": [75, 620], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [18, 1265], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [14, 2892], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
