[
    {
        "choices": ["牆料", "版料", "AB車道版", "住料", "樑料", "下層版筋", "預留筋", "柱料", "上層版筋"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": [], "hashtag": False, "names": ["號數"], "range": None, "sequence": False, "type": "str"},
    {
        "choices": ["ㄇ字型", "閉合箍", "總重量", "版馬椅 一前一後", "U字型", "直料", "單頭", "雙頭"],
        "hashtag": False,
        "names": ["名稱"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["料長"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [0, 31043], "sequence": False, "type": "int"},
    {
        "choices": ["牆料", "版料", "AB車道版", "住料", "樑料", "下層版筋", "預留筋", "柱料", "上層版筋"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": [], "hashtag": False, "names": ["號數"], "range": None, "sequence": False, "type": "str"},
    {
        "choices": ["ㄇ字型", "閉合箍", "總重量", "版馬椅 一前一後", "U字型", "直料", "單頭", "雙頭"],
        "hashtag": False,
        "names": ["名稱"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["料長"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [0, 31043], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["備註"], "range": [0, 31043], "sequence": False, "type": "int"},
]
