[
    {
        "choices": ["續接器", "牆料", "樑料", "預留筋", "版料"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "choices": ["單頭", "公頭彎勾", "直料"],
        "hashtag": False,
        "names": ["名稱"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["料長"], "range": [50, 760], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [3, 348], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [18, 5800], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
    {
        "choices": ["續接器", "牆料", "樑料", "預留筋", "版料"],
        "hashtag": False,
        "names": ["部位"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {"choices": None, "hashtag": True, "names": ["號數"], "range": [0, 8], "sequence": False, "type": "int"},
    {
        "choices": ["單頭", "公頭彎勾", "直料"],
        "hashtag": False,
        "names": ["名稱"],
        "range": None,
        "sequence": None,
        "type": "str",
    },
    {
        "names": [
            "圖示",
            "施工內容",
            "加工形狀",
            "加工型狀",
            "加工形式",
            "加工型式",
            "形狀",
            "型狀",
            "形式",
            "型式",
            "料型",
            "料形",
        ],
        "type": "str",
        "empty": False,
        "hashtag": False,
        "sequence": False,
        "range": None,
        "choices": None,
    },
    {"choices": None, "hashtag": False, "names": ["料長"], "range": [50, 760], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["支數"], "range": [3, 348], "sequence": False, "type": "int"},
    {"choices": None, "hashtag": False, "names": ["重量"], "range": [18, 5800], "sequence": False, "type": "int"},
    {"choices": [], "hashtag": False, "names": ["備註"], "range": None, "sequence": None, "type": "str"},
]
